import * as React from "react";
import { View, Linking } from "react-native";
import {
  Paragraph,
  Subheading,
  List,
  Button,
  Divider,
} from "react-native-paper";

const PrivacyPolicy = () => {
  const goToURL = (url) => {
    Linking.canOpenURL(url).then((supported) => {
      if (supported) {
        Linking.openURL(url);
      } else {
        console.log("Unable to open this URL: " + url);
      }
    });
  };
  return (
    <View>
      <Subheading>Simple version:</Subheading>
      <Paragraph>
        We do not aim to collect any information about you, your device, or any
        information entered into the app. There are no mechanisms in place to
        send your data to any external parties, nor search your device for
        anything else.
      </Paragraph>
      <Paragraph>
        This app stores your To Do items solely on your device (no external
        backups) in an unencrypted form.
      </Paragraph>
      <Divider style={{ marginVertical: 10 }} />
      <Subheading>Legal Version</Subheading>
      <Paragraph>
        My To Do App (“we,” “our,” or “us”) is committed to protecting your
        privacy. This Privacy Policy explains how your personal information is
        collected, used, and disclosed by My To Do App.
      </Paragraph>
      <Paragraph>
        This Privacy Policy applies to our website, and its associated
        subdomains (collectively, our “Service”) alongside our application, My
        To Do App. By accessing or using our Service, you signify that you have
        read, understood, and agree to our collection, storage, use, and
        disclosure of your personal information as described in this Privacy
        Policy and our Terms of Service.
      </Paragraph>
      <Subheading>Definitions and key terms</Subheading>
      <Paragraph>
        To help explain things as clearly as possible in this Privacy Policy,
        every time any of these terms are referenced, are strictly defined as:
      </Paragraph>
      <List.Section>
        <List.Item
          title="Cookie:"
          descriptionNumberOfLines={40}
          description="Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information."
        />
        <List.Item
          title="Company:"
          descriptionNumberOfLines={40}
          description="When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Miles BD Consulting Inc. that is responsible for your information under this Privacy Policy."
        />
        <List.Item
          title="Country:"
          descriptionNumberOfLines={40}
          description="Where My To Do App or the owners/founders of My To Do App are based, in this case is Canada"
        />
        <List.Item
          title="Customer:"
          descriptionNumberOfLines={40}
          description="Refers to the company, organization or person that signs up to use the My To Do App Service to manage the relationships with your consumers or service users."
        />
        <List.Item
          title="Device:"
          descriptionNumberOfLines={40}
          description="Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit My To Do App and use the services."
        />
        <List.Item
          title="IP address:"
          descriptionNumberOfLines={40}
          description="Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet."
        />
        <List.Item
          title="Personnel:"
          descriptionNumberOfLines={40}
          description="Refers to those individuals who are employed by My To Do App or are under contract to perform a service on behalf of one of the parties."
        />
        <List.Item
          title="Personal Data:"
          descriptionNumberOfLines={40}
          description="Any information that directly, indirectly, or in person."
        />
        <List.Item
          title="Service:"
          descriptionNumberOfLines={40}
          description="Refers to the service provided by My To Do App as described in the relative terms (if available) and on this platform."
        />
        <List.Item
          title="Third-party service:"
          descriptionNumberOfLines={40}
          description="Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you."
        />
        <List.Item
          title="Website:"
          descriptionNumberOfLines={40}
          description="My To Do App's site, which can be accessed via this URL:"
        />
        <List.Item
          title="You:"
          descriptionNumberOfLines={40}
          description="A person or entity that is registered with My To Do App to use the Services."
        />
      </List.Section>
      <Subheading>Information automatically collected</Subheading>
      <Paragraph>
        We do not collect any information when using the application.
      </Paragraph>
      <Subheading>Governing Law</Subheading>
      <Paragraph>
        This Privacy Policy is governed by the laws of Canada without regard to
        its conflict of laws provision. You consent to the exclusive
        jurisdiction of the courts in connection with any action or dispute
        arising between the parties under or in connection with this Privacy
        Policy except for those individuals who may have rights to make claims
        under Privacy Shield, or the Swiss-US framework.
      </Paragraph>
      <Paragraph>
        The laws of Canada, excluding its conflicts of law rules, shall govern
        this Agreement and your use of the app. Your use of the app may also be
        subject to other local, state, national, or international laws.
      </Paragraph>
      <Paragraph>
        By using My To Do App or contacting us directly, you signify your
        acceptance of this Privacy Policy. If you do not agree to this Privacy
        Policy, you should not engage with our website, or use our services.
        Continued use of the website, direct engagement with us, or following
        the posting of changes to this Privacy Policy that do not significantly
        affect the use or disclosure of your personal information will mean that
        you accept those changes.
      </Paragraph>

      <Subheading>Your Consent</Subheading>
      <Paragraph>
        We've updated our Privacy Policy to provide you with complete
        transparency into what is being set when you visit our site and how it's
        being used. By using our app, registering an account, or making a
        purchase, you hereby consent to our Privacy Policy and agree to its
        terms.
      </Paragraph>

      <Subheading>Links to Other Websites</Subheading>
      <Paragraph>
        This Privacy Policy applies only to the Services. The Services may
        contain links to other websites not operated or controlled by My To Do
        App. We are not responsible for the content, accuracy or opinions
        expressed in such websites, and such websites are not investigated,
        monitored or checked for accuracy or completeness by us. Please remember
        that when you use a link to go from the Services to another website, our
        Privacy Policy is no longer in effect. Your browsing and interaction on
        any other website, including those that have a link on our platform, is
        subject to that website’s own rules and policies. Such third parties may
        use their own cookies or other methods to collect information about you.
      </Paragraph>

      <Subheading>Kids' Privacy</Subheading>
      <Paragraph>
        We do not collect information from kids under the age of 13 just to
        better our services.
      </Paragraph>
      <Subheading>Changes To Our Privacy Policy</Subheading>
      <Paragraph>
        We may change our Service and policies, and we may need to make changes
        to this Privacy Policy so that they accurately reflect our Service and
        policies. Unless otherwise required by law, we will notify you (for
        example, through our Service) before we make changes to this Privacy
        Policy and give you an opportunity to review them before they go into
        effect. Then, if you continue to use the Service, you will be bound by
        the updated Privacy Policy. If you do not want to agree to this or any
        updated Privacy Policy, you can delete your account.
      </Paragraph>

      <Subheading>Third-Party Services</Subheading>
      <Paragraph>
        We may display, include or make available third-party content (including
        data, information, applications and other products services) or provide
        links to third-party websites or services ("Third- Party Services").
      </Paragraph>
      <Paragraph>
        You acknowledge and agree that My To Do App shall not be responsible for
        any Third-Party Services, including their accuracy, completeness,
        timeliness, validity, copyright compliance, legality, decency, quality
        or any other aspect thereof. My To Do App does not assume and shall not
        have any liability or responsibility to you or any other person or
        entity for any Third-Party Services.
      </Paragraph>
      <Paragraph>
        Third-Party Services and links thereto are provided solely as a
        convenience to you and you access and use them entirely at your own risk
        and subject to such third parties' terms and conditions.
      </Paragraph>
      <Subheading>
        Information about General Data Protection Regulation (GDPR)
      </Subheading>
      <Paragraph>
        We may be collecting and using information from you if you are from the
        European Economic Area (EEA), and in this section of our Privacy Policy
        we are going to explain exactly how and why is this data collected, and
        how we maintain this data under protection from being replicated or used
        in the wrong way.
      </Paragraph>

      <Subheading>What is GDPR?</Subheading>
      <Paragraph>
        GDPR is an EU-wide privacy and data protection law that regulates how EU
        residents' data is protected by companies and enhances the control the
        EU residents have, over their personal data.
      </Paragraph>
      <Paragraph>
        The GDPR is relevant to any globally operating company and not just the
        EU-based businesses and EU residents. Our customers’ data is important
        irrespective of where they are located, which is why we have implemented
        GDPR controls as our baseline standard for all our operations worldwide.
      </Paragraph>

      <Subheading>What is personal data?</Subheading>
      <Paragraph>
        Any data that relates to an identifiable or identified individual. GDPR
        covers a broad spectrum of information that could be used on its own, or
        in combination with other pieces of information, to identify a person.
        Personal data extends beyond a person’s name or email address. Some
        examples include financial information, political opinions, genetic
        data, biometric data, IP addresses, physical address, sexual
        orientation, and ethnicity.
      </Paragraph>
      <Paragraph>
        The Data Protection Principles include requirements such as:
      </Paragraph>

      <List.Item
        title="Personal data"
        descriptionNumberOfLines={40}
        description="Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect."
      />
      <List.Item
        title="Personal data"
        descriptionNumberOfLines={40}
        description="Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it."
      />
      <List.Item
        title="Personal data"
        descriptionNumberOfLines={40}
        description="Personal data should be held no longer than necessary to fulfil its purpose."
      />
      <List.Item
        title="People"
        descriptionNumberOfLines={40}
        description="People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization."
      />

      <Subheading>Why is GDPR important?</Subheading>
      <Paragraph>
        GDPR adds some new requirements regarding how companies should protect
        individuals' personal data that they collect and process. It also raises
        the stakes for compliance by increasing enforcement and imposing greater
        fines for breach. Beyond these facts it's simply the right thing to do.
        At My To Do App we strongly believe that your data privacy is very
        important and we already have solid security and privacy practices in
        place that go beyond the requirements of this new regulation.
      </Paragraph>

      <Subheading>
        Individual Data Subject's Rights - Data Access, Portability and Deletion
      </Subheading>
      <Paragraph>
        We are committed to helping our customers meet the data subject rights
        requirements of GDPR. While My To Do App does not process or store any
        personal data, we do you may contact us with any GDPR data requests.
      </Paragraph>
      <Subheading>California Residents</Subheading>
      <Paragraph>
        The California Consumer Privacy Act (CCPA) requires us to disclose
        categories of Personal Information we collect and how we use it, the
        categories of sources from whom we collect Personal Information, and the
        third parties with whom we share it, which we have explained above.
      </Paragraph>
      <Paragraph>
        We are also required to communicate information about rights California
        residents have under California law. You may exercise the following
        rights:
      </Paragraph>
      <List.Item
        title="Right to Know and Access."
        descriptionNumberOfLines={40}
        description="You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you."
      />
      <List.Item
        title="Right to Equal Service."
        descriptionNumberOfLines={40}
        description="We will not discriminate against you if you exercise your privacy rights."
      />
      <List.Item
        title="Right to Delete."
        descriptionNumberOfLines={40}
        description="You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected."
      />
      <List.Item
        title="Request"
        descriptionNumberOfLines={40}
        description="Request that a business that sells a consumer's personal data, not sell the consumer's personal data."
      />
      <Paragraph>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </Paragraph>
      <Paragraph>
        We do not sell the Personal Information of our users.
      </Paragraph>
      <Paragraph>
        For more information about these rights, please contact us.
      </Paragraph>
      <Subheading>
        California Online Privacy Protection Act (CalOPPA)
      </Subheading>
      <Paragraph>
        CalOPPA requires us to disclose categories of Personal Information we
        collect and how we use it, the categories of sources from whom we
        collect Personal Information, and the third parties with whom we share
        it, which we have explained above.
      </Paragraph>
      <Paragraph>CalOPPA users have the following rights:</Paragraph>

      <List.Item
        title="Right to Know and Access."
        descriptionNumberOfLines={40}
        description="You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you."
      />
      <List.Item
        title="Right to Equal Service."
        descriptionNumberOfLines={40}
        description="We will not discriminate against you if you exercise your privacy rights."
      />
      <List.Item
        title="Right to Delete."
        descriptionNumberOfLines={40}
        description="You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected."
      />
      <List.Item
        title="Right to request"
        descriptionNumberOfLines={40}
        description="Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data."
      />

      <Paragraph>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </Paragraph>
      <Paragraph>
        We do not sell the Personal Information of our users.
      </Paragraph>
      <Paragraph>
        For more information about these rights, please contact us.
      </Paragraph>
      <Subheading>Contact Us</Subheading>
      <Paragraph>
        Don't hesitate to contact us if you have any questions. Via email:
      </Paragraph>
      <Button
        compact={true}
        uppercase={false}
        accessibilityLabel="Contact us via email about privacy concerns"
        labelStyle={{ flexDirection: "row", justifyContent: "flex-start" }}
        onPress={() =>
          goToURL(
            "mailto:privacy@milesbd.ca?subject=Privacy Concern with 'My To Do' app"
          )
        }
      >
        privacy@milesbd.ca
      </Button>
      <Divider style={{ marginVertical: 10 }} />
      <Paragraph>Last Updated: 2024-02-05</Paragraph>
    </View>
  );
};

export default React.memo(PrivacyPolicy);
